POST http://localhost:3000/posts
Content-Type: application/json

{ "Username":"Carona1", "Password":"4rodas", "Limite": "4", "Vagas": "4", "interesses": ""} 

###
GET http://localhost:3000/       
Content-Type: application/json

{ "_id": "5eb794615d629a3010da14b7"} 

### lista de interessados.
GET http://localhost:3000/intere      
Content-Type: application/json

{ "_id": "5e8638eb4da2aa41a0d9d99e"} 


###
PUT  http://localhost:3000/att
Content-Type: application/json

{"_id": "5eb6f03f4c09491a50719226"} 


###

PUT  http://localhost:3000/interesse
Content-Type: application/json

{"_id": "5eb79230e5d5f326b4fad8b1"} 


###

PUT  http://localhost:3000/inte
Content-Type: application/json

{"_id": "5eb7946b5d629a3010da14b8", "interesse": "id do cara2"} 


###
DELETE   http://localhost:3000/dell
Content-Type: application/json

{"_id": "5e8638db4da2aa41a0d9d99d" } 




###
GET http://localhost:3000/logi
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.MTIzNDU2.uTOeleGuWdOvcmqMRFQMtXL3nB8NMzJT61x2Z89eEfM


###
POST  http://localhost:3000/login
Content-Type: application/json
// apenas usado no server2.js
{ "Username": "caio"} 





